language: cpp

branches:
  only:
    - ci-test-release

os:
  - linux

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qt5-default qttools5-dev-tools

script:
  - lrelease res/lang/en.ts
  - qmake apkstudio.pro CONFIG+=release
  - make

  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage

  - mkdir apkstudio-latest-release
  - cd apkstudio-latest-release
  - cp ../apkstudio .

  - ../linuxdeployqt*.AppImage apkstudio -bundle-non-qt-libs -no-translations -verbose=2
  - ls -al

  - rm -rf doc AppRun .DirIcon
  - cd  lib && mv libQt5Core.so.5 libQt5Gui.so.5 libQt5Widgets.so.5 .. && rm -r * && mv ../libQ* . && cd ..
#  - find ./lib/ ! -name 'libQt*' -type f -exec rm -f {} + && rm lib/libQt5DBus.so.5 lib/libQt5XcbQpa.so.5
  - rm -rf plugins/imageformats/ plugins/platforminputcontexts/ plugins/xcbglintegrations/

  - cd ..
  - tar -zvcf apkstudio-latest-release.tar.gz apkstudio-latest-release

  - ./apkstudio-latest-release/apkstudio