language: cpp

branches:
  only:
    - ci-test-release

os:
  - linux

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qt5-default qttools5-dev-tools

script:
  - lrelease res/lang/en.ts
  - qmake apkstudio.pro CONFIG+=release
  - make
  - mkdir apkstudio-latest-release
  - cd apkstudio-latest-release
  - cp ../apkstudio .
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - ./linuxdeployqt*.AppImage apkstudio -bundle-non-qt-libs -no-translations -verbose=1
  - ls
  - rm -rf doc AppRun .DirIcon
  - find ./lib/ ! -name 'libQt*' -type f -exec rm -f {} + && rm lib/libQt5DBus.so.5 lib/libQt5XcbQpa.so.5
  - rm -rf plugins/imageformats/ plugins/platforminputcontexts/ plugins/xcbglintegrations/

  - tar -zvcf apkstudio-latest-release.tar.gz ../apkstudio-latest-release

  - ./apkstudio